# these files cascade and build the base config of our linting
inherit_from:
  - https://raw.githubusercontent.com/talentplatforms/shared-rubocop/master/.talentplatforms-rubocop.yml
  - .rubocop_todo.yml

AllCops:
  SuggestExtensions: false
  NewCops: enable
